name: docker-build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# permissions are needed if pushing to ghcr.io
permissions:
    packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.RELEASE_VERSION }}
          submodules: 'true'

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Archive
        run: yarn archive
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}, ghcr.io/${{ github.repository }}:latest